version: '3'
services:
    postgres:
        image: postgres
        container_name: Postgres
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
        ports:
            - "5432:5432"
        restart: always
        networks:
            net:
                ipv4_address: 10.10.0.2

    pgadmin:
        image: dpage/pgadmin4
        container_name: Pgadmin
        environment:
            PGADMIN_DEFAULT_EMAIL: ogzhner5@gmail.com
            PGADMIN_DEFAULT_PASSWORD: root
        ports:
            - "5443:443"
            - "8080:80"
        restart: always
        networks:
            net:
                ipv4_address: 10.10.0.3

    orderservice:
        image: orderservice
        container_name: orderservice
        restart: always
        ports:
            - "5010:5000"
        networks:
            net:
                ipv4_address: 10.10.0.4

networks:
  net:
    ipam:
      driver: default
      config:
        - subnet: 10.10.0.0/24
