version: '3'
services:
    postgres:
        image: postgres
        container_name: Postgres
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
        ports:
            - "5432:5432"
        restart: always
        networks:
            - net

    pgadmin:
        image: dpage/pgadmin4
        container_name: Pgadmin
        environment:
            PGADMIN_DEFAULT_EMAIL: ogzhner5@gmail.com
            PGADMIN_DEFAULT_PASSWORD: root
        ports:
            - "5443:443"
            - "8080:80"
        restart: always
        networks:
            - net

    orderservice:
        image: orderservice
        container_name: orderservice
        restart: always
        ports:
            - "5010:5000"
        networks:
            - net

    rabbitmq:
        image: rabbitmq:management
        container_name: rabbitmq
        environment:
            RABBITMQ_DEFAULT_USER: guest
            RABBITMQ_DEFAULT_PASS: guest
        ports:
            - "5672:5672"
            - "15672:15672"
        restart: always
        networks:
            - net

networks:
  net:
    ipam:
      driver: default
      config:
        - subnet: 10.10.0.0/24
